#!/bin/bash

# Read the VERSIONS.env file and generate versions.hcl
THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
VERSIONS_ENV="$THIS_DIR/../config/VERSIONS.env"
TEMP_FILE=$(mktemp)

# Start with an empty file
> "$TEMP_FILE"

echo "# This file is auto-generated from VERSIONS.env" > "$TEMP_FILE"
echo "# Do not edit this file directly." >> "$TEMP_FILE"
echo "" >> "$TEMP_FILE"

# Read VERSIONS.env and generate variables
while IFS='=' read -r key value; do
    # Skip empty lines and comments
    [[ -z "$key" || "$key" =~ ^# ]] && continue
    
    # Remove any quotes from the value and trailing whitespace
    value=$(echo "$value" | tr -d '"' | tr -d "'" | xargs)
    key=$(echo "$key" | xargs)

    # Generate the variable block
    cat >> "$TEMP_FILE" << EOF
variable "$key" {
    default = "$value"
    description = "The version of ${key%_VERSION} to use in the Dockerfile."
}

EOF
done < "$VERSIONS_ENV"


echo "target \"_versions\" {" >> "$TEMP_FILE"
echo "    args = {" >> "$TEMP_FILE"

# Add all variables to the args block
while IFS='=' read -r key value; do
    [[ -z "$key" || "$key" =~ ^# ]] && continue
    key=$(echo "$key" | xargs)
    echo "        $key = \"\${$key}\"" >> "$TEMP_FILE"
done < "$VERSIONS_ENV"

# Close the blocks
echo "    }" >> "$TEMP_FILE"
echo "}" >> "$TEMP_FILE"

cat "${TEMP_FILE}"
