# This file is auto-generated from VERSIONS.env
# Do not edit this file directly.

variable "MONGO_TOOLS_VERSION" {
    default = "100.12.1"
    description = "The version of MONGO_TOOLS to use in the Dockerfile."
}

variable "MONGOSH_VERSION" {
    default = "2.5.1"
    description = "The version of MONGOSH to use in the Dockerfile."
}

variable "PYTHON_VERSION" {
    default = "3.12.5"
    description = "The version of PYTHON to use in the Dockerfile."
}

variable "UBUNTU_VERSION" {
    default = "24.04"
    description = "The version of UBUNTU to use in the Dockerfile."
}

variable "JAVA_VERSION" {
    default = "17.0.14"
    description = "The version of JAVA to use in the Dockerfile."
}

variable "TOMCAT_VERSION" {
    default = "9.0.107"
    description = "The version of TOMCAT to use in the Dockerfile."
}

variable "MAVEN_VERSION" {
    default = "3.9.8"
    description = "The version of MAVEN to use in the Dockerfile."
}

variable "NODE_VERSION" {
    default = "20.17.0"
    description = "The version of NODE to use in the Dockerfile."
}

variable "MONGO_VERSION" {
    default = "8.0.5"
    description = "The version of MONGO to use in the Dockerfile."
}

variable "WF_NODE_VERSION" {
    default = "18.20.5"
    description = "The version of WF_NODE to use in the Dockerfile."
}

variable "YQ_VERSION" {
    default = "4.45.1"
    description = "The version of YQ to use in the Dockerfile."
}

variable "TERRAFORM_VERSION" {
    default = "1.9.8"
    description = "The version of TERRAFORM to use in the Dockerfile."
}

target "_versions" {
    args = {
        MONGO_TOOLS_VERSION = "${MONGO_TOOLS_VERSION}"
        MONGOSH_VERSION = "${MONGOSH_VERSION}"
        PYTHON_VERSION = "${PYTHON_VERSION}"
        UBUNTU_VERSION = "${UBUNTU_VERSION}"
        JAVA_VERSION = "${JAVA_VERSION}"
        TOMCAT_VERSION = "${TOMCAT_VERSION}"
        MAVEN_VERSION = "${MAVEN_VERSION}"
        NODE_VERSION = "${NODE_VERSION}"
        MONGO_VERSION = "${MONGO_VERSION}"
        WF_NODE_VERSION = "${WF_NODE_VERSION}"
        YQ_VERSION = "${YQ_VERSION}"
        TERRAFORM_VERSION = "${TERRAFORM_VERSION}"
    }
}
